\c organizer_dashboard;

INSERT INTO Zone (zone_name) VALUES
('A'),
('B'),
('C'),
('D');

--com
INSERT INTO Building (building_ID, zone_ID, building_name, description, exhibits, exhibit_tags) VALUES
(22, 1, '22. Drawing Office 2 ', 'Industry and VR Zone,Smart City by PeraCom', ARRAY[
    'Smart Power Socket',
    'Interactive personal assistant device (P-E-BO)',
    'Smart Indoor Light Control & Automation System',
    'A Smart Wearable for Home Control and Security (Smart light/socket/ lock with gesture)',
    'Remote Gait Analysis',
    'Medicine Dispenser',
    'NearIR medical analysis (2'' x 4'')',
    'Oral Cancer Screening Booth (OASIS AI App)',
    'Immersive AI-Driven Nursing Education:',
    'Drone based smart agriculture management system',
    'Monitoring and controlling soilless agricultural plantations (Modular hydroponic system)',
    'CMS (A system to manage and monitor cattle)',
    'Smart Environmental Monitoring System for Palm Oil Plantation in Watawala',
    'Industrial Workers'' Smart Safety Helmet',
    'Sea Pollution Detection',
    'Smart land surveying device',
    'VR Golf',
    'Hackers Club',
    'The Robot Waiter',
    'Pera Ride',
    'Rail Ticekting',
    'PeraSwarm Setup',
    'CNC based Pick and Place Arm',
    'Neuromorphic',
    'FPGA',
    'AI-Assisted Quality Assessment for RCT Using IOPA Radiographs',
    'BCI for Inner Speech Classification',
    'Smart Traffic Light System',
    'golf game',
    'Smorphi setup',
    'Robot arm game',
    'obstacle robotos',
    'PeraVerse Exhibition Management System'
],
'
{
    "Smart Power Socket": ["Electronics and Embedded Systems"],
    "Interactive personal assistant device (P-E-BO)": ["Electronics and Embedded Systems"],
    "Smart Indoor Light Control & Automation System": ["Electronics and Embedded Systems", "Information Technology and Computing", "Science, Entertainment and Mathematics of Engineering"],
    "A Smart Wearable for Home Control and Security (Smart light/socket/ lock with gesture)": ["Artificial Intelligence Machine Learning and Data Science", "Electronics and Embedded Systems"],
    "Remote Gait Analysis": ["Biomedical Engineering and Mechatronics", "Electronics and Embedded Systems"],
    "Medicine Dispenser": ["Electronics and Embedded Systems", "Robotics , Automation and Manufacturing"],
    "NearIR medical analysis (2'' x 4'')": ["Biomedical Engineering and Mechatronics", "Electronics and Embedded Systems"],
    "Oral Cancer Screening Booth (OASIS AI App)": ["Artificial Intelligence Machine Learning and Data Science", "Biomedical Engineering and Mechatronics", "Electronics and Embedded Systems"],
    "Immersive AI-Driven Nursing Education:": ["Artificial Intelligence Machine Learning and Data Science", "Biomedical Engineering and Mechatronics", "Electronics and Embedded Systems"],
    "Drone based smart agriculture management system": ["Electronics and Embedded Systems", "Robotics , Automation and Manufacturing", "Energy Environment and Sustainability & Nature Based Technologies"],
    "Monitoring and controlling soilless agricultural plantations (Modular hydroponic system)": ["Electronics and Embedded Systems", "Robotics , Automation and Manufacturing", "Information Technology and Computing", "Energy Environment and Sustainability & Nature Based Technologies"],
    "CMS (A system to manage and monitor cattle)": ["Electronics and Embedded Systems", "Energy Environment and Sustainability & Nature Based Technologies"],
    "Smart Environmental Monitoring System for Palm Oil Plantation in Watawala": ["Artificial Intelligence Machine Learning and Data Science", "Electronics and Embedded Systems", "Energy Environment and Sustainability & Nature Based Technologies"],
    "Industrial Workers'' Smart Safety Helmet": ["Electronics and Embedded Systems", "Energy Environment and Sustainability & Nature Based Technologies"],
    "Sea Pollution Detection": ["Electronics and Embedded Systems", "Energy Environment and Sustainability & Nature Based Technologies"],
    "Smart land surveying device": ["Electronics and Embedded Systems", "Energy Environment and Sustainability & Nature Based Technologies"],
    "VR Golf": ["Electronics and Embedded Systems", "Science, Entertainment and Mathematics of Engineering"],
    "Hackers Club": ["Electronics and Embedded Systems", "Science, Entertainment and Mathematics of Engineering"],
    "The Robot Waiter": ["Electronics and Embedded Systems", "Robotics , Automation and Manufacturing"],
    "Pera Ride": ["Electronics and Embedded Systems", "Energy Environment and Sustainability & Nature Based Technologies"],
    "Rail Ticekting": ["Electronics and Embedded Systems", "Information Technology and Computing"],
    "PeraSwarm Setup": ["Artificial Intelligence Machine Learning and Data Science", "Electronics and Embedded Systems", "Robotics , Automation and Manufacturing", "Science, Entertainment and Mathematics of Engineering"],
    "CNC based Pick and Place Arm": ["Robotics , Automation and Manufacturing", "Science, Entertainment and Mathematics of Engineering"],
    "Neuromorphic": ["Artificial Intelligence Machine Learning and Data Science"],
    "FPGA": ["Artificial Intelligence Machine Learning and Data Science", "Biomedical Engineering and Mechatronics"],
    "AI-Assisted Quality Assessment for RCT Using IOPA Radiographs": ["Artificial Intelligence Machine Learning and Data Science"],
    "BCI for Inner Speech Classification": ["Artificial Intelligence Machine Learning and Data Science"],
    "Smart Traffic Light System": ["Electronics and Embedded Systems"],
    "golf game": ["Science, Entertainment and Mathematics of Engineering"],
    "Smorphi setup": ["Electronics and Embedded Systems"],
    "Robot arm game": ["Electronics and Embedded Systems", "Science, Entertainment and Mathematics of Engineering"],
    "obstacle robotos": ["Electronics and Embedded Systems", "Science, Entertainment and Mathematics of Engineering"],
    "PeraVerse Exhibition Management System": ["Electronics and Embedded Systems", "Information Technology and Computing"]
}
'
);

INSERT INTO Building (
    building_ID, 
    zone_ID, 
    building_name, 
    description, 
    exhibits, 
    exhibit_tags
) VALUES
(
    3, 
    2, 
    '3. Drawing Office 1', 
    'EngMath Nexus, School Innovation Hub & Computer Museum', 
    ARRAY[
        'Optical Illusions',
        'Quiz',
        'Maths in Fine Arts',
        'Escape Room',
        'Double Pendulum',
        'Harmonograph Exhibit',
        'Galton Board with Pascal''s Triangle',
        'Geometrical Shapes in Water with Math',
        'ICT museum',
        'Digital Twin',
        'Educational/Digital Circuit Design',
        'Project OMEGA : SAP Computer',
        'Awakening The IBM 1130',
        'Apollo Computer'
    ],
    '{
        "Optical Illusions": ["Science, Entertainment and Mathematics of Engineering"],
        "Quiz": ["Science, Entertainment and Mathematics of Engineering"],
        "Maths in Fine Arts": ["Science, Entertainment and Mathematics of Engineering"],
        "Escape Room": ["Science, Entertainment and Mathematics of Engineering"],
        "Double Pendulum": ["Science, Entertainment and Mathematics of Engineering"],
        "Harmonograph Exhibit": ["Science, Entertainment and Mathematics of Engineering"],
        "Galton Board with Pascal''s Triangle": ["Science, Entertainment and Mathematics of Engineering"],
        "Geometrical Shapes in Water with Math": ["Science, Entertainment and Mathematics of Engineering"],
        "ICT museum": ["Information Technology and Computing"],
        "Digital Twin": [],
        "Educational/Digital Circuit Design": ["Electronics and Embedded Systems"],
        "Project OMEGA : SAP Computer": ["Electronics and Embedded Systems", "Information Technology and Computing"],
        "Awakening The IBM 1130": ["Artificial Intelligence Machine Learning and Data Science", "Electronics and Embedded Systems", "Information Technology and Computing"],
        "Apollo Computer": ["Electronics and Embedded Systems"]
    }'
);

--chem
INSERT INTO Building (
    building_ID, 
    zone_ID, 
    building_name, 
    description, 
    exhibits, 
    exhibit_tags
) VALUES
(
    1, 
    2, 
    '1. Department of Chemical Engineering', 
    'Chemical Engineering: Innovating a Greener Tomorrow', 
    ARRAY[
        'Optimization of Biomass Briquettes Produced from Algae and Coir Dust',
        'Pilot-Scale Treatment System with Detoxification Unit for Hospital Wastewater',
        'Development of an AI-Powered Assistant for Reactor Design',
        'Biomass Fuel Upgrading through Torrefaction',
        'Sustainable biodiesel production',
        'Nano corner exhibits',
        'Photo-bio reactor',
        'To develop a reliable gas leakage detection system for LPG, and other inflammable gases',
        'Working module of Meewatura water treatment plant'
    ],
    '{
        "Optimization of Biomass Briquettes Produced from Algae and Coir Dust": ["Energy Environment and Sustainability & Nature Based Technologies"],
        "Pilot-Scale Treatment System with Detoxification Unit for Hospital Wastewater": ["Energy Environment and Sustainability & Nature Based Technologies"],
        "Development of an AI-Powered Assistant for Reactor Design": ["Artificial Intelligence Machine Learning and Data Science", "Information Technology and Computing"],
        "Biomass Fuel Upgrading through Torrefaction": ["Energy Environment and Sustainability & Nature Based Technologies"],
        "Sustainable biodiesel production": ["Energy Environment and Sustainability & Nature Based Technologies"],
        "Nano corner exhibits": ["Materials and Nanotechnology"],
        "Photo-bio reactor": ["Energy Environment and Sustainability & Nature Based Technologies"],
        "To develop a reliable gas leakage detection system for LPG, and other inflammable gases": ["Electronics and Embedded Systems"],
        "Working module of Meewatura water treatment plant": ["Energy Environment and Sustainability & Nature Based Technologies"]
    }'
);


INSERT INTO Building (building_ID, zone_ID, building_name, description, exhibits, exhibit_tags) VALUES
(11, 3, '11. Surveying Lab', 'Smart Mobility Hub', ARRAY[
    'Photo Gallery on Road Safety',
    'Evolution of Survey Instruments',
    'Scale model of Kandy Multimodal Transport Terminal (KMTT)',
    'Planetarium'
],
'
{
    "Photo Gallery on Road Safety": ["Road Safety, Transportation Planning and Engineering Survey"],
    "Evolution of Survey Instruments": ["Road Safety, Transportation Planning and Engineering Survey"],
    "Scale model of Kandy Multimodal Transport Terminal (KMTT)": ["Road Safety, Transportation Planning and Engineering Survey"],
    "Planetarium": ["Road Safety, Transportation Planning and Engineering Survey"]
}
'
);

INSERT INTO Building (building_ID, zone_ID, building_name, description, exhibits, exhibit_tags) VALUES
(
    13, 
    3, 
    '13. Materials Lab', 
    'Chemical Engineering Pilot Plant: From Lab to Industry,Sustainable and Resilient Structures', 
    ARRAY[
        'Natural fibre reinforced composites',
        'Herringbone dome structure',
        'Kohu Kreations',
        'Architectured Materials',
        'Liquid Extractor',
        'Distillation column',
        'Climbing film Evaporator',
        'Multi Effect Evaporator',
        'Fermenter',
        'Crystallizer',
        'Build-a-Bridge and Stand a Chance to Win',
        'Rhythm of Structures',
        'Strength Beyond Limits',
        'From Lime to Legacy',
        'Unseen Threats'
    ],
    '{
        "Natural fibre reinforced composites": ["Energy Environment and Sustainability & Nature Based Technologies"],
        "Herringbone dome structure": ["Energy Environment and Sustainability & Nature Based Technologies"],
        "Kohu Kreations": ["Energy Environment and Sustainability & Nature Based Technologies"],
        "Architectured Materials": ["Materials and Nanotechnology"],
        "Liquid Extractor": ["Pilot Plant"],
        "Distillation column": ["Pilot Plant"],
        "Climbing film Evaporator": ["Pilot Plant"],
        "Multi Effect Evaporator": ["Pilot Plant"],
        "Fermenter": ["Pilot Plant"],
        "Crystallizer": ["Pilot Plant"],
        "Build-a-Bridge and Stand a Chance to Win": ["Structural Engineering"],
        "Rhythm of Structures": ["Structural Engineering"],
        "Strength Beyond Limits": ["Structural Engineering"],
        "From Lime to Legacy": ["Materials and Nanotechnology"],
        "Unseen Threats": ["Structural Engineering"]
    }'
);

INSERT INTO Building (building_ID, zone_ID, building_name, description, exhibits, exhibit_tags) VALUES
(
    12, 
    3, 
    '12. Soil Lab', 
    'GeoFrontiers Hub', 
    ARRAY[
        'Tunnel section and Tunnel boring machine',
        'Rock & Mineral Samples',
        'Geology/ Weathering Profile',
        'Full Geotechnical Model',
        'Foundation & Ground Improvement',
        'Rail Track',
        'Slope Stability and Remedial Measures',
        'Liquefaction',
        'Retaining Walls',
        'Moragahakanda Dam',
        'Basic Geotechnical',
        'Elevated Highway',
        'Soil Heave Model'
    ],
    '{
        "Tunnel section and Tunnel boring machine": ["Geology and Geotechnical Engineering"],
        "Rock & Mineral Samples": ["Geology and Geotechnical Engineering"],
        "Geology/ Weathering Profile": ["Geology and Geotechnical Engineering"],
        "Full Geotechnical Model": ["Geology and Geotechnical Engineering"],
        "Foundation & Ground Improvement": ["Geology and Geotechnical Engineering"],
        "Rail Track": ["Geology and Geotechnical Engineering"],
        "Slope Stability and Remedial Measures": ["Geology and Geotechnical Engineering"],
        "Liquefaction": ["Geology and Geotechnical Engineering"],
        "Retaining Walls": ["Geology and Geotechnical Engineering"],
        "Moragahakanda Dam": ["Geology and Geotechnical Engineering"],
        "Basic Geotechnical": ["Geology and Geotechnical Engineering"],
        "Elevated Highway": ["Road Safety, Transportation Planning and Engineering Survey", "Geology and Geotechnical Engineering"],
        "Soil Heave Model": ["Geology and Geotechnical Engineering"]
    }'
);


INSERT INTO Building (building_ID, zone_ID, building_name, description, exhibits, exhibit_tags) VALUES
(
    18, 
    4, 
    '18. Thermodynamics Lab', 
    'Applied Thermodynamics, Automobiles and Aeronautical Zone', 
    ARRAY[
        'Biomimetic fog harvester design-Phase 1, #1',
        'Solar cooker',
        'Mercet''s Boiler',
        'Redwood viscometer',
        'Junker''s Calorimeter',
        'Bomb Clarimeter',
        'Forbes Marhall Boiler demonstration',
        'Steam distribution system',
        'Power generation',
        'Steam Engine',
        'Cold Room',
        'Ammonia Refrigerator',
        'Vapor compression',
        'Heat Exchanger',
        'Forced Convection',
        'Microchannel evaporator performance in a refrigeration system with propane as refrigerant',
        'Performance analysis of R290 and R32 in air-conditioning systems',
        'Analysis of flammable refrigerant leaks through CFD simulation and risk assessment to enhance industrial safety',
        'Steam radiator for a Tea Dryer',
        'Studying biomass boiler performance and the effect of operating parameters on performance and emissions and ways to optimize performance',
        'Formula Student electric race car fabrication',
        'Gearbox cut sections & components',
        'Vehicle model setup',
        'Valve Timing demonstration',
        'Cam & Cranks ,Pistons',
        'Engine oils',
        'Tyres',
        'Hybrid car',
        'Automobile lab setup',
        'Net Zero Building + Smart Home',
        'Wing Morphing Mechanism',
        'Quadcopter PID Controller Test Rig',
        'VTOL RC Aircraft',
        'Wing Mechanisms',
        'Rolls-Royce Turbofan Engine Restoration',
        'Rotary-Type Aircraft Engine (Cut Section)',
        'AN-32B Engines with propellers (17 x 7)',
        'Bell 206 Helicopter Engine and Transmission - 1 (14'' x 6'')',
        'Vertical Stabilizer (cut view, MiG-27, 11'' x 3'')',
        'Kfir Aircraft Ejection Seat (7'' x 6'')',
        'Mi-17 APU Working model (6'' x 6'')',
        'Bell 212 Helicopter',
        'Model Runway (7 x 7)',
        'Wind Tunnel',
        'wave energy lab',
        'Survival Pack',
        'Screw turbine'
    ],
    '{
        "Biomimetic fog harvester design-Phase 1, #1": ["Renewable energy and sustainability"],
        "Solar cooker": ["Renewable energy and sustainability"],
        "Mercet''s Boiler": ["Applied Thermodynamics"],
        "Redwood viscometer": ["Applied Thermodynamics"],
        "Junker''s Calorimeter": ["Applied Thermodynamics"],
        "Bomb Clarimeter": ["Applied Thermodynamics"],
        "Forbes Marhall Boiler demonstration": ["Applied Thermodynamics"],
        "Steam distribution system": ["Applied Thermodynamics"],
        "Power generation": ["Applied Thermodynamics"],
        "Steam Engine": ["Applied Thermodynamics"],
        "Cold Room": ["Applied Thermodynamics"],
        "Ammonia Refrigerator": ["Applied Thermodynamics"],
        "Vapor compression": ["Applied Thermodynamics"],
        "Heat Exchanger": ["Applied Thermodynamics"],
        "Forced Convection": ["Applied Thermodynamics"],
        "Microchannel evaporator performance in a refrigeration system with propane as refrigerant": ["Applied Thermodynamics"],
        "Performance analysis of R290 and R32 in air-conditioning systems": ["Applied Thermodynamics"],
        "Analysis of flammable refrigerant leaks through CFD simulation and risk assessment to enhance industrial safety": ["Applied Thermodynamics"],
        "Steam radiator for a Tea Dryer": ["Applied Thermodynamics"],
        "Studying biomass boiler performance and the effect of operating parameters on performance and emissions and ways to optimize performance": ["Applied Thermodynamics"],
        "Formula Student electric race car fabrication": ["Automobile"],
        "Gearbox cut sections & components": ["Automobile"],
        "Vehicle model setup": ["Automobile"],
        "Valve Timing demonstration": ["Automobile"],
        "Cam & Cranks ,Pistons": ["Automobile"],
        "Engine oils": ["Automobile"],
        "Tyres": ["Automobile"],
        "Hybrid car": ["Automobile"],
        "Automobile lab setup": ["Automobile"],
        "Net Zero Building + Smart Home": ["Cyber physical"],
        "Wing Morphing Mechanism": ["aeronautical"],
        "Quadcopter PID Controller Test Rig": ["aeronautical"],
        "VTOL RC Aircraft": ["aeronautical"],
        "Wing Mechanisms": ["aeronautical"],
        "Rolls-Royce Turbofan Engine Restoration": ["aeronautical"],
        "Rotary-Type Aircraft Engine (Cut Section)": ["aeronautical"],
        "AN-32B Engines with propellers (17 x 7)": ["aeronautical"],
        "Bell 206 Helicopter Engine and Transmission - 1 (14'' x 6'')": ["aeronautical"],
        "Vertical Stabilizer (cut view, MiG-27, 11'' x 3'')": ["aeronautical"],
        "Kfir Aircraft Ejection Seat (7'' x 6'')": ["aeronautical"],
        "Mi-17 APU Working model (6'' x 6'')": ["aeronautical"],
        "Bell 212 Helicopter": ["aeronautical"],
        "Model Runway (7 x 7)": ["aeronautical"],
        "Wind Tunnel": ["aeronautical"],
        "wave energy lab": ["Renewable energy and sustainability"],
        "Survival Pack": ["aeronautical"],
        "Screw turbine": ["Renewable energy and sustainability"]
    }'
);

INSERT INTO Building (building_ID, zone_ID, building_name, description, exhibits, exhibit_tags) VALUES
(
    17, 
    4, 
    '17. Applied Mechanics Lab', 
    'Applied Mechanics & Cyber Physical Systems', 
    ARRAY[
        'Inverted Pendulum',
        'Robot Arm',
        'Yogurt Machine',
        'AGV',
        'FPGA',
        'CNC',
        'Twin Rotor',
        'Segway',
        'Underwater Robot',
        'Golf Analysis (Wearable)',
        'Plastic Sorting',
        'HVAC Control',
        'Turbo Charger',
        'Turbo Charger for Diesel Engine',
        'Self Locking Friction Jack',
        'Balancing of Rotors',
        'Static Balancing Equipment',
        'Two Storey Building Structure',
        'Tech Equipment',
        'Wind Excited Vibration of a Structural Model',
        'Tacoma Bridge',
        'Differential (Motor Vehicle Differential / Crown Wheel & Pinion)',
        'Gear and Power Transmission',
        'Outboard Motor Gear Box',
        'Servo Mechanism',
        'Gyroscope',
        'Hartnell Governor Apparatus',
        'Control System',
        'Pumps, Compressors and Fluid System',
        'Mechanisms',
        'Compound Pendulums'
    ],
    '{
        "Inverted Pendulum": ["Cyber physical"],
        "Robot Arm": ["Cyber physical"],
        "Yogurt Machine": ["Cyber physical"],
        "AGV": ["Cyber physical"],
        "FPGA": ["Cyber physical"],
        "CNC": ["Cyber physical"],
        "Twin Rotor": ["Cyber physical"],
        "Segway": ["Cyber physical"],
        "Underwater Robot": ["Cyber physical"],
        "Golf Analysis (Wearable)": ["Cyber physical"],
        "Plastic Sorting": ["Cyber physical"],
        "HVAC Control": ["Cyber physical"],
        "Turbo Charger": ["Applied Mechanics"],
        "Turbo Charger for Diesel Engine": ["Applied Mechanics"],
        "Self Locking Friction Jack": ["Applied Mechanics"],
        "Balancing of Rotors": ["Applied Mechanics"],
        "Static Balancing Equipment": ["Applied Mechanics"],
        "Two Storey Building Structure": ["Applied Mechanics"],
        "Tech Equipment": ["Applied Mechanics"],
        "Wind Excited Vibration of a Structural Model": ["Applied Mechanics"],
        "Tacoma Bridge": ["Applied Mechanics"],
        "Differential (Motor Vehicle Differential / Crown Wheel & Pinion)": ["Applied Mechanics"],
        "Gear and Power Transmission": ["Applied Mechanics"],
        "Outboard Motor Gear Box": ["Applied Mechanics"],
        "Servo Mechanism": ["Applied Mechanics"],
        "Gyroscope": ["Applied Mechanics"],
        "Hartnell Governor Apparatus": ["Applied Mechanics"],
        "Control System": ["Applied Mechanics"],
        "Pumps, Compressors and Fluid System": ["Applied Mechanics"],
        "Mechanisms": ["Applied Mechanics"],
        "Compound Pendulums": ["Applied Mechanics"]
    }'
);

INSERT INTO Building (building_ID, zone_ID, building_name, description, exhibits, exhibit_tags) VALUES
(16, 4, '16.New Mechanics Lab', 'Renewable Energy and Sustainability', ARRAY[
    'Bio Gas/ Syn gas',
    'Biofuel progression',
    'Wind turbine for expressway power harvesting Energy',
    'Rainwater Energy harvester system',
    'Vertical axis wind turbine with guided vanes',
    'Future farms : smart hydroponics',
    'Smart City concept',
    'RePET Filament maker',
    'Biomimetic fog harvester design - Phase I, II'
],
'
{
    "Bio Gas/ Syn gas": ["Renewable energy and sustainability"],
    "Biofuel progression": ["Renewable energy and sustainability"],
    "Wind turbine for expressway power harvesting Energy": ["Renewable energy and sustainability"],
    "Rainwater Energy harvester system": ["Renewable energy and sustainability"],
    "Vertical axis wind turbine with guided vanes": ["Renewable energy and sustainability"],
    "Future farms : smart hydroponics": ["Renewable energy and sustainability"],
    "Smart City concept": ["Renewable energy and sustainability"],
    "RePET Filament maker": ["Renewable energy and sustainability"],
    "Biomimetic fog harvester design - Phase I, II": ["Renewable energy and sustainability"]
}'
);


INSERT INTO Building (building_ID, zone_ID, building_name, description, exhibits, exhibit_tags) VALUES
(28, 1, '28.Department of Manufacturing And Industrial Engineering', 'Creovate DMIE', ARRAY[
    'Metal Additive Manufacturing',
    'Soft Robotic Gripper for Efficient Grasping of Irregular objects (Design & Development of Grasping Robot Arms)',
    'Granular Jamming-Based Robotic Grasping for Manipulation of Complex Shapes (Design & Development of Grasping Robot Arms)',
    'Design and Fabrication of a 3D Concrete Printing Machine for Sustainable Construction Applications',
    'Design and development of a digital product passport to communicate product sustainability and circularity options.',
    'Sorting Mechanism by using 6DF Robot Arm and Machine Learning',
    'Mecanum Wheel Bluetooth Robot Car',
    'Delta Robot Development Project',
    'Improving the Delta Robot in the Department for Real-Time Object Sorting',
    'Remaining Useful Life Time Prediction of Bearings using Machine Learning',
    'Automated Guided Goods Carrier',
    'Coordinated Control and Communication Strategies for Swarm Drones in Autonomous Missions',
    'Simulate Ceramic Production Process to Improve the Throughput and Reduce Waste',
    'EcoChain: Bridging Farmers and Buyers via Economic Centers',
    'Home Automation System using DTMF',
    'Powder surface area analyzer',
    'Electronic Nose for Quality Analysis of Food and Dairy Products',
    'Digital Densitometer for Liquid Density and Powder Particle Analysis',
    'Low-Power Pure Sine Wave Inverter with Automatic Grid Switching',
    'Hot Wire Anemometer',
    'White-Light Reflectometer for Industrial Color Matching',
    'High-Voltage Ozone Generator for Water Treatment',
    'Footstep Power Generation System',
    'Automatic Cake Design Icing Machine',
    'DIY Laser Engraver for Personalized Fabrication',
    '3D Wonder Tech',
    'Smart Medicine Packaging and Labelling Machine',
    'Augmented Reality (AR) / Virtual Reality (VR) demonstration',
    'Design and Development of an Automated Gem Cutting Machine',
    'Arduino flex sensor controlled robotic hand project',
    'Development and Implementation of a Fully Automated Breakdown Reporting and Management System for Production Lines',
    'DMIE Smart Labs Project',
    'CIM Center + ABB',
    'Injection Molding Machine',
    'Friction Stir Welding Samples and the Weld Tools',
    'Ansell + DMIE Collaboration Zone',
    'Glove Manufacturing Simulation',
    'Dynamic Impact Analysis'
],
'
{
    "Metal Additive Manufacturing": ["Manufacturing & Industrial"],
    "Soft Robotic Gripper for Efficient Grasping of Irregular objects (Design & Development of Grasping Robot Arms)": ["Robotics & Automation"],
    "Granular Jamming-Based Robotic Grasping for Manipulation of Complex Shapes (Design & Development of Grasping Robot Arms)": ["Robotics & Automation"],
    "Design and Fabrication of a 3D Concrete Printing Machine for Sustainable Construction Applications": ["Manufacturing & Industrial"],
    "Design and development of a digital product passport to communicate product sustainability and circularity options.": ["Software, Digital Solutions & Emerging Tech"],
    "Sorting Mechanism by using 6DF Robot Arm and Machine Learning": ["Robotics & Automation"],
    "Mecanum Wheel Bluetooth Robot Car": ["Robotics & Automation"],
    "Delta Robot Development Project": ["Robotics & Automation"],
    "Improving the Delta Robot in the Department for Real-Time Object Sorting": ["Robotics & Automation"],
    "Remaining Useful Life Time Prediction of Bearings using Machine Learning": ["Machine Learning, AI & Smart Systems"],
    "Automated Guided Goods Carrier": ["Robotics & Automation"],
    "Coordinated Control and Communication Strategies for Swarm Drones in Autonomous Missions": ["Machine Learning, AI & Smart Systems"],
    "Simulate Ceramic Production Process to Improve the Throughput and Reduce Waste": ["Manufacturing & Industrial"],
    "EcoChain: Bridging Farmers and Buyers via Economic Centers": [],
    "Home Automation System using DTMF": ["Software, Digital Solutions & Emerging Tech"],
    "Powder surface area analyzer": ["Electrical, Electronics & Instrumentation"],
    "Electronic Nose for Quality Analysis of Food and Dairy Products": ["Electrical, Electronics & Instrumentation"],
    "Digital Densitometer for Liquid Density and Powder Particle Analysis": ["Electrical, Electronics & Instrumentation"],
    "Low-Power Pure Sine Wave Inverter with Automatic Grid Switching": ["Electrical, Electronics & Instrumentation"],
    "Hot Wire Anemometer": ["Electrical, Electronics & Instrumentation"],
    "White-Light Reflectometer for Industrial Color Matching": ["Electrical, Electronics & Instrumentation"],
    "High-Voltage Ozone Generator for Water Treatment": ["Electrical, Electronics & Instrumentation"],
    "Footstep Power Generation System": ["Electrical, Electronics & Instrumentation"],
    "Automatic Cake Design Icing Machine": ["Robotics & Automation"],
    "DIY Laser Engraver for Personalized Fabrication": ["Robotics & Automation"],
    "3D Wonder Tech": ["Manufacturing & Industrial", "Software, Digital Solutions & Emerging Tech"],
    "Smart Medicine Packaging and Labelling Machine": ["Software, Digital Solutions & Emerging Tech"],
    "Augmented Reality (AR) / Virtual Reality (VR) demonstration": ["Software, Digital Solutions & Emerging Tech"],
    "Design and Development of an Automated Gem Cutting Machine": ["Robotics & Automation"],
    "Arduino flex sensor controlled robotic hand project": ["Robotics & Automation"],
    "Development and Implementation of a Fully Automated Breakdown Reporting and Management System for Production Lines": ["Machine Learning, AI & Smart Systems"],
    "DMIE Smart Labs Project": ["Machine Learning, AI & Smart Systems"],
    "CIM Center + ABB": ["Manufacturing & Industrial"],
    "Injection Molding Machine": ["Manufacturing & Industrial"],
    "Friction Stir Welding Samples and the Weld Tools": ["Manufacturing & Industrial"],
    "Ansell + DMIE Collaboration Zone": ["Manufacturing & Industrial"],
    "Glove Manufacturing Simulation": ["Manufacturing & Industrial"],
    "Dynamic Impact Analysis": ["Manufacturing & Industrial"]
}'
);

INSERT INTO Building (building_ID, zone_ID, building_name, description, exhibits, exhibit_tags) VALUES
(8, 3, '8.Department of Electrical and Electronic Engineering', 'Spark Street DEEE', ARRAY[
    'AI Traffic Violation Detection System',
    'Virtual Mouse Using Computer Vision',
    'G07 Transmittance and Reflectance Imaging for Quality Assessment in Agriculture and Manufacturing',
    'G59 Satellite Image Based Remote Sensing for Change Detection and Landscape Mapping',
    'G28 AI Based Solutions for Human - Elephant Conflicts in Sri Lanka',
    'Quality Evaluation System for Videos and Images Using AI and ML',
    'G33 Frictionless Attendance Tracking',
    'Smart Calculator',
    'Improving vehicle number plate visibility via low resolution cctv video enhancement',
    'Selfie translation through OCR',
    'AI for Automated Biomedical Image Processing',
    'ECG, SpO2 and Pulse Rate Analysis for Heart Disease Prediction',
    'EMS Controlled Robotic Arm',
    'Multi-Sensor Cardiovascular Disease Prediction',
    'G18 Bio Medical Radar',
    'Urine Flow Meter',
    'Design and Performance Evaluation of a Helical Antenna Based GPS Receiver Front End',
    'AM Modulator',
    'FM Modulator',
    'Digital Modulation',
    'Telecommunication Setup',
    'Moisture Measurement Setup (Sct)',
    'Dual Antenna based Locating System',
    'Wave Guide Audio Transmitter',
    'Smart Greenhouse Monitoring and Control System Using IF!X SCADA',
    'Autonomous Vehicle for Objects Detection and Attacking',
    'Dynamic Wireless Charging System for Electric Vehicles (EVs)',
    'Smart Fire Distinguishing Robot',
    'Self Learning RPS Game using perceptrons',
    'Track Vibration Detecting System',
    'Soft PLC for Precision Agriculture Applications',
    'IoT Based Predictive Maintenance Using Vibrational Analysis',
    'Water quality monitoring system',
    'Smart Sensor Network for Structural Health Monitoring',
    'G14 Design and Development of a Hybrid Inverter for Domestic Solar PV Systems',
    'G29 AgriVoltaics EV Charging Station',
    'Intrusive Load Monitoring Device',
    'Plasma Speaker',
    'Renewable energy installations on Highways',
    'Ion Thruster',
    'Vision Navigated Agricultural UGV',
    'G03 Light Sensing and Control of an AgriVoltaic Plant',
    'AI For Wearable Technology',
    'Multispectral Imaging System for Agricultural Applications',
    'G32 Localization with only a RFID Handheld Reader',
    'Real-Time Air Quality Measurement Using a UAV Drone',
    'Driverless e-Wheeler',
    'Self-Driving Mobile Robot',
    'G11 Indo-Lanka Power Grid Linkages: Evaluating Technical, Social, and Economic Dimensions in a Deregulated',
    'AI based power transformer moisture estimation',
    'AI based power transformer fault identification',
    'AI-imaged based condition assessment of conductors',
    'AI-imaged based condition assessment of lightning surge arresters',
    'AI based hybrid hydro-solar energy optimization : case study at Samanalawewa reservoir',
    'sri Lankan power transmission network',
    'frequency spectrum for condition monitoring and renewable power applications',
    'One Sun One World One Grid (OSOWOG) concept',
    'Electric Pump Performance Analyzer',
    'Modern Energy-Efficient Smart Home',
    'AI based hybrid hydro-solar energy optimization : case study at Samanalawewa reservoir',
    'Sri Lanka Blackout Implementation',
    'G26 Improving Vehicle Number Plate Visibility via Low-Resolution Video Enhancement',
    'G24 Clear Sight for Drivers: Robust Road and Traffic Sign Recognition for ADAS Under Adverse Weather Conditions',
    'Gesture Control Omni Wheel Robot',
    'Gesture Controlling + GPS Navigation Robot',
    'G27 Vision-Guided Reinforcement Learning for Autonomous Mobile Robot Path Planning in Unknown Environments',
    'Robotics Labs Equipments (Robotic Arm, Inverted Pendulum, Twin Rotor)'
],
'
{
    "AI Traffic Violation Detection System": ["Artificial Intelligence Machine Learning and Data Science"],
    "Virtual Mouse Using Computer Vision": ["Artificial Intelligence Machine Learning and Data Science"],
    "G07 Transmittance and Reflectance Imaging for Quality Assessment in Agriculture and Manufacturing": ["Artificial Intelligence Machine Learning and Data Science"],
    "G59 Satellite Image Based Remote Sensing for Change Detection and Landscape Mapping": ["Artificial Intelligence Machine Learning and Data Science"],
    "G28 AI Based Solutions for Human - Elephant Conflicts in Sri Lanka": ["Artificial Intelligence Machine Learning and Data Science"],
    "Quality Evaluation System for Videos and Images Using AI and ML": ["Artificial Intelligence Machine Learning and Data Science"],
    "G33 Frictionless Attendance Tracking": ["Artificial Intelligence Machine Learning and Data Science"],
    "Smart Calculator": ["Artificial Intelligence Machine Learning and Data Science"],
    "Improving vehicle number plate visibility via low resolution cctv video enhancement": ["Artificial Intelligence Machine Learning and Data Science"],
    "Selfie translation through OCR": ["Artificial Intelligence Machine Learning and Data Science"],
    "AI for Automated Biomedical Image Processing": ["Biomedical Engineering and Mechatronics"],
    "ECG, SpO2 and Pulse Rate Analysis for Heart Disease Prediction": ["Biomedical Engineering and Mechatronics"],
    "EMS Controlled Robotic Arm": ["Biomedical Engineering and Mechatronics"],
    "Multi-Sensor Cardiovascular Disease Prediction": ["Biomedical Engineering and Mechatronics"],
    "G18 Bio Medical Radar": ["Biomedical Engineering and Mechatronics"],
    "Urine Flow Meter": ["Biomedical Engineering and Mechatronics"],
    "Design and Performance Evaluation of a Helical Antenna Based GPS Receiver Front End": ["Communication and Information Engineering (CIE)"],
    "AM Modulator": ["Communication and Information Engineering (CIE)"],
    "FM Modulator": ["Communication and Information Engineering (CIE)"],
    "Digital Modulation": ["Communication and Information Engineering (CIE)"],
    "Telecommunication Setup": ["Communication and Information Engineering (CIE)"],
    "Moisture Measurement Setup (Sct)": ["Communication and Information Engineering (CIE)"],
    "Dual Antenna based Locating System": ["Communication and Information Engineering (CIE)"],
    "Wave Guide Audio Transmitter": ["Communication and Information Engineering (CIE)"],
    "Smart Greenhouse Monitoring and Control System Using IF!X SCADA": ["Control, Robotics and Automation Engineering (RCA)"],
    "Autonomous Vehicle for Objects Detection and Attacking": ["Control, Robotics and Automation Engineering (RCA)"],
    "Dynamic Wireless Charging System for Electric Vehicles (EVs)": ["Control, Robotics and Automation Engineering (RCA)"],
    "Smart Fire Distinguishing Robot": ["Control, Robotics and Automation Engineering (RCA)"],
    "Self Learning RPS Game using perceptrons": ["Electronics and Instrumentation Engineering (EI)"],
    "Track Vibration Detecting System": ["Electronics and Instrumentation Engineering (EI)"],
    "Soft PLC for Precision Agriculture Applications": ["Electronics and Instrumentation Engineering (EI)"],
    "IoT Based Predictive Maintenance Using Vibrational Analysis": ["Electronics and Instrumentation Engineering (EI)"],
    "Water quality monitoring system": ["Electronics and Instrumentation Engineering (EI)"],
    "Smart Sensor Network for Structural Health Monitoring": ["Electronics and Instrumentation Engineering (EI)"],
    "G14 Design and Development of a Hybrid Inverter for Domestic Solar PV Systems": ["Power High Voltage and Energy Systems Engineering (PHE)"],
    "G29 AgriVoltaics EV Charging Station": ["Power High Voltage and Energy Systems Engineering (PHE)"],
    "Intrusive Load Monitoring Device": ["Power High Voltage and Energy Systems Engineering (PHE)"],
    "Plasma Speaker": ["Power High Voltage and Energy Systems Engineering (PHE)"],
    "Renewable energy installations on Highways": ["Power High Voltage and Energy Systems Engineering (PHE)"],
    "Ion Thruster": ["Power High Voltage and Energy Systems Engineering (PHE)"],
    "Vision Navigated Agricultural UGV": ["Power High Voltage and Energy Systems Engineering (PHE)"],
    "G03 Light Sensing and Control of an AgriVoltaic Plant": ["Artificial Intelligence and Signal Processing (AISP)"],
    "AI For Wearable Technology": ["Artificial Intelligence and Signal Processing (AISP)"],
    "Multispectral Imaging System for Agricultural Applications": ["Communication and Information Engineering (CIE)"],
    "G32 Localization with only a RFID Handheld Reader": ["Electronics and Instrumentation Engineering (EI)"],
    "Real-Time Air Quality Measurement Using a UAV Drone": ["Control, Robotics and Automation Engineering (RCA)"],
    "Driverless e-Wheeler": ["Control, Robotics and Automation Engineering (RCA)"],
    "Self-Driving Mobile Robot": ["Control, Robotics and Automation Engineering (RCA)"],
    "G11 Indo-Lanka Power Grid Linkages: Evaluating Technical, Social, and Economic Dimensions in a Deregulated": ["Power High Voltage and Energy Systems Engineering (PHE)"],
    "AI based power transformer moisture estimation": ["Power High Voltage and Energy Systems Engineering (PHE)"],
    "AI based power transformer fault identification": ["Power High Voltage and Energy Systems Engineering (PHE)"],
    "AI-imaged based condition assessment of conductors": ["Power High Voltage and Energy Systems Engineering (PHE)"],
    "AI-imaged based condition assessment of lightning surge arresters": ["Power High Voltage and Energy Systems Engineering (PHE)"],
    "AI based hybrid hydro-solar energy optimization : case study at Samanalawewa reservoir": ["Power High Voltage and Energy Systems Engineering (PHE)"],
    "sri Lankan power transmission network": ["Power High Voltage and Energy Systems Engineering (PHE)"],
    "frequency spectrum for condition monitoring and renewable power applications": ["Power High Voltage and Energy Systems Engineering (PHE)"],
    "One Sun One World One Grid (OSOWOG) concept": ["Power High Voltage and Energy Systems Engineering (PHE)"],
    "Electric Pump Performance Analyzer": ["Power High Voltage and Energy Systems Engineering (PHE)"],
    "Modern Energy-Efficient Smart Home": ["Power High Voltage and Energy Systems Engineering (PHE)"],
    "Sri Lanka Blackout Implementation": ["Power High Voltage and Energy Systems Engineering (PHE)"],
    "G26 Improving Vehicle Number Plate Visibility via Low-Resolution Video Enhancement": ["Artificial Intelligence and Signal Processing (AISP)"],
    "G24 Clear Sight for Drivers: Robust Road and Traffic Sign Recognition for ADAS Under Adverse Weather Conditions": ["Artificial Intelligence and Signal Processing (AISP)"],
    "Gesture Control Omni Wheel Robot": ["Control, Robotics and Automation Engineering (RCA)"],
    "Gesture Controlling + GPS Navigation Robot": ["Control, Robotics and Automation Engineering (RCA)"],
    "G27 Vision-Guided Reinforcement Learning for Autonomous Mobile Robot Path Planning in Unknown Environments": ["Control, Robotics and Automation Engineering (RCA)"],
    "Robotics Labs Equipments (Robotic Arm, Inverted Pendulum, Twin Rotor)": ["Control, Robotics and Automation Engineering (RCA)"]
}'
);



INSERT INTO Building (building_ID, zone_ID, building_name, description, exhibits, exhibit_tags) VALUES
(9, 3, '9.Department of Electrical and Electronic Engineering', 'Dream Zone', ARRAY[
    'CANVAS : Cinema, AI, Novel Visual Arts & Science (Lecture Room 3)',
    'SONIC : Sound Oriented Novel Instruments and Creations (Lecture Room 2)'
],
'
{
    "CANVAS : Cinema, AI, Novel Visual Arts & Science (Lecture Room 3)": ["Communication and Information Engineering (CIE)"],
    "SONIC : Sound Oriented Novel Instruments and Creations (Lecture Room 2)": ["Communication and Information Engineering (CIE)"]
}'
);







-- EVENTS--
INSERT INTO Events (event_name, start_time, end_time, location, description, event_categories) VALUES
('Last Flight To Mars (On 23rd)', '2025-09-23 10:00:00', '2025-09-23 19:00:00', 'Manufacturing department''s exhibit', 'There are three chambers. 1st is an space lab, 2nd is a rover, 3rd is the final destination.', ARRAY['Arts', 'Games']),
('Bridge Competition Session 1 ', '2025-09-23 10:00:00', '2025-09-23 14:00:00', 'Material lab', 'we are aiming the school students for this competition', ARRAY['Games']),
('Bridge Competition Session 2 ', '2025-09-23 15:00:00', '2025-09-23 19:00:00', 'Material lab', 'we are aiming the school students for this competition', ARRAY['Games']),
('Drone show', '2025-09-23 18:30:00', '2025-09-23 18:41:00', 'In front of AR', 'Coordinator name is nipun. Starting time can vary due to weather.', ARRAY['Technology', 'Arts']),
('3D project mapping', '2025-09-23 18:42:00', '2025-09-23 19:00:00', 'AR building', 'After drone show', ARRAY['Technology', 'Arts']),
('Triden co operation drone demo', '2025-09-23 11:00:00', '2025-09-23 16:00:00', 'In front of manu dep', 'Live experience of agricultural and sur valent', ARRAY['Technology', 'Science', 'Education', 'Robotics']);

